### PR TITLE
fix build with kernel < 5.9

### PR DESCRIPTION
**Pull request by ffontaine**
`linux/close_range.h` is only available since kernel 5.9 and https://github.com/torvalds/linux/commit/60997c3d45d9a67daf01c56d805ae4fec37e0bd8 resulting in the following build failure:

```
catatonit.c:39:11: fatal error: linux/close_range.h: No such file or directory
   39 | # include <linux/close_range.h>
      |           ^~~~~~~~~~~~~~~~~~~~~
```

Fixes:
 - http://autobuild.buildroot.org/results/ed9a847905083175c7fcb2f2df28f9ac5b9c3313

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Can you please rebase this? We have changed the license from GPL-3.0-or-later to GPL-2.0-or-later and we need you to rebase it in order to confirm that you agree with the new license terms.

**Comment by ffontaine** [comment]
Done

**Comment by cyphar** [comment]
I did a proper rebase (`git rebase origin/main`) to clean up the history. Thanks for the patch!
